### ISSUE TITLE
In 1.10.0.0 with "Tension belts activated" tension belts are no longer fixed

### ISSUE THREAD

**Issue by vitalii2011** [Achimobil/FS22_aPalletAutoLoader#10]
Fixed after "Disable Autoload":

https://user-images.githubusercontent.com/41552153/236623555-d6d3f608-dd68-42ee-9668-cbc903c6c732.mp4

So in 1.9.0.0:

https://user-images.githubusercontent.com/41552153/236623591-759739c0-2000-4eb0-964f-7be5b6e9dff4.mp4

**Comment by Achimobil** [comment]
That is what it now has to be. The AL holds the pallets self on place util it is deactivated either because of full or because of you disable it self.

**Comment by vitalii2011** [comment]
Thanks for clarifying.
