### ISSUE TITLE
Ladeliste individuell kürzen

### ISSUE THREAD

**Issue by RWTH-MK** [Achimobil/FS22_aPalletAutoLoader#22]
Ich habe diverse Ladegüter, die ich schlicht nie einsetze (z.B. BigBag Paletten, diverse Ballengrößen). Neben der oder alternativ zur jetzt geplanten Automatischen Auswahl könnte man vielleicht zu Fuß ein Menü öffnen, um festzulegen, welche Ladegüter der AL überhaupt zur Wahl haben soll? Das würde die Liste sicherlich auch schon verkürzen und erübrigen, jeden AL Mod anzupassen (gerade im MP ein immenser und nur mühsam reversibler Aufwand)

**Comment by Achimobil** [comment]
Ist die Frage ob das dann pro Fahrzeug, Pro user oder generell sein sollte. Aber schlecht ist die idee nicht.

**Comment by Achimobil** [comment]
Im 22er gibt es keine Features mehr. Ob im 25er ein AL von mir kommt lasse ich an der stelle offen, weil ich es noch nicht weiß.
