### ISSUE TITLE
Ist es möglich, AL zu Pakete hinzuzufügen?

### ISSUE THREAD

**Issue by vitalii2011** [Achimobil/FS22_aPalletAutoLoader#31]
![fsScreen_2024_02_08_20_07_29](https://github.com/Achimobil/FS22_aPalletAutoLoader/assets/41552153/cb0f5aba-fc29-42a1-8ce9-9359a608f206)

**Comment by Achimobil** [comment]
Intresting idea. I will take a look if that is a possibility to have all AL based vehicles in such a package. 
If I do not find I will ask loki how to do.

**Comment by vitalii2011** [comment]
Yes, Loki knows. At one time, GtX told him this at my request.

**Comment by Achimobil** [comment]
Eingebaut in 1.12.0.3

**Comment by vitalii2011** [comment]
Danke.
