### ISSUE TITLE
Paletten von der Giants-Mod Straw Harvest werden nicht geladen

### ISSUE THREAD

**Issue by ToothyDev** [Achimobil/FS22_aPalletAutoLoader#32]
Alles andere wird perfekt aufgeladen, aber die Pellet-Paletten, die aus der neuen Pellethalle der StrawHarvest Mod kommen, nicht. Es müsten Europalette-Übergröße Paletten sein... die Anzahl der Paletten wird auch vernünftig angezeigt, aber sie laden sich einfach nicht auf.

**Comment by Achimobil** [comment]
Das ist korrekt. Das Straw Harvest ist kein Mod von Giants und deshalb unterstützt der Basismod diese Paletten auch nicht.
Hier muss entweder CM die Paletten in Standardgröße machen, den auch Übergroße passen nicht, oder CM muss in seinen Mod ein Extension Skript rein packen. 
Alternativ warten bis ich irgendwann eine Extension dafür selbst veröffentliche, aber dafür hat der Mod aus meiner Sicht noch zu viele Fehler. Wie dass die Paletten zu den filltypes nicht korrekt registriert sind, die Trigger in einigen Paletten fehlen und auch die filltypes nicht eingetragen sind in der products Kategorie. Daneben noch haufenweise gemeldete lua fehler in den Discords. Also gedult und es wird nicht im Autoload Basis mod rein kommen.

Das es nicht in den Basis Mod kommt ist eine Generelle Entscheidung. Jeder Modder der was anderes Machen will an Paletten als Giants vorgibt im Standard muss eine eigene Erweiterung machen oder sich an die von mir vorgegebene Verzeichnissstruktur halten. Ansonsten mache ich jede woche eine neue Version vom AL nur weil sich wieder einer was anderes ausgedacht hat. Ist vielleicht schön für die Downloadzahlen des AL aber nicht zielführend.

So, der nächste der Fragen wird hier hin verwiesen, keine lust das immer wieder zu schreiben. Ich wollte aber auch nicht einfach nur "Kommt nicht, muss der Modder selbst machen" schreiben ;)

**Comment by ToothyDev** [comment]
Passt, hab ne andere autoload mod gefunden die es unterstützt. Zu sagen dass es keine Giants Mod ist find ich allerdings auch sehr witzig

**Comment by Achimobil** [comment]
Wieso findest du das Witzig? Es ist nicht von Giants sondern von CM

**Comment by ToothyDev** [comment]
Das mag ja sein dass es von anderen Entwicklern kommt, aber auf jeden Fall im Auftrag von Giants. Sonst hätte es keine offiziellen Announcements dazu gegeben, oder meinst du, Giants promoted auf einmal fremde Mods sowohl auf Steam als auch auf der Giants Website?

**Comment by Achimobil** [comment]
Die Promoten das weil CM auch ein DLC gemacht hat. Damit ist es trotzdem nicht offiziell von Giants.
