### ISSUE TITLE
AL Abstand von BigBags

### ISSUE THREAD

**Issue by andreasthu** [Achimobil/FS22_aPalletAutoLoader#33]
Hallo Achimobil
mit ist der Abstand von den Big Bags beim AL laden etwas zu weit vorgekommen.
hab nun mal testweise in der FS22_aPalletAutoLoader/APalletAutoLoader.lua (ab zeile 1272) die xbzw z werte um 5cm verringert, also auf:
```
		autoLoadObject.CheckTypeMethod = CheckType
		-- autoLoadObject.sizeX = 1
		autoLoadObject.sizeX = 0.95
		autoLoadObject.sizeY = 1.55
		-- autoLoadObject.sizeZ = 0.85
		autoLoadObject.sizeZ = 0.80
		autoLoadObject.type = "bigBag"
		autoLoadObject.stackable = false
		autoLoadObject.pickupTriggerCollisionMask = CollisionFlag.TRIGGER_VEHICLE;
```
 also x von 1 auf 0.95
und z von 0.85 auf 0.80

nun stehen die BigBags nicht mehr so einzeln auf der Ladefläche herum sondern sind etwas aneinander angelehnt:
 ![fsScreen_2024_03_08_07_31_50](https://github.com/Achimobil/FS22_aPalletAutoLoader/assets/24860501/1b52a06f-deba-4a51-9b60-8517726d0095)
![fsScreen_2024_03_08_07_31_56](https://github.com/Achimobil/FS22_aPalletAutoLoader/assets/24860501/e929cd88-9032-4ff4-94ae-d527cfad02ac)
![fsScreen_2024_03_08_07_32_00](https://github.com/Achimobil/FS22_aPalletAutoLoader/assets/24860501/422c94be-55ce-4b5d-88ec-f4d15047d943)
(außerdem passen dann 6 anstelle 4 auf den Lindner Unitrac)
es wären sogar sixeX = 0.9 und sizeZ = 0.75 möglich und machbar , aber 0.95 bzw 0.80 reicht mir auch schon.
lg
andreas

**Comment by Achimobil** [comment]
Schau mal bitte ob dann auch halb gefüllte Bigbags noch funktionineren.
Die sind der grund gewesen für den abstand, da diese breiter werden, wenn sie nicht voll sind.
Wenn das kein problem ist übernehme ich die Werte gern für das nächste Update für alle

**Comment by andreasthu** [comment]
Hallo Achimobil
wie gewünscht - hier, 6x halbvolle Bigbags (500L je Sack)
![fsScreen_2024_03_08_18_03_36](https://github.com/Achimobil/FS22_aPalletAutoLoader/assets/24860501/f662a199-12cd-4302-aaff-2a0ba6f65a0e)
![fsScreen_2024_03_08_18_04_12](https://github.com/Achimobil/FS22_aPalletAutoLoader/assets/24860501/90351336-6e03-4f44-b4e8-0cd419a7cdb4)
![fsScreen_2024_03_08_18_04_21](https://github.com/Achimobil/FS22_aPalletAutoLoader/assets/24860501/9c1ed324-3d95-4871-9ac6-66e5fc446006)
mir scheint sogar, das nun mehr platz ist, d.h. die säcke sind im vergleich zu den screenshots mit vollen Säcken kleiner.
lg
andreas
edit:
habs vergessen, leider macht mein ls22 seit dem letzten update mit der Druck taste nurmehr screenshots ohne interface
liegt an fsr3, würd ich das deaktivieren hätt ich auch screenshots mit interface aber auch weniger fps

**Comment by Achimobil** [comment]
Dann werde ich das in das nächste Update mit übernehmen, finden andere bestimmt auch gut wenn ja nach ladefläche was mehr drauf passt ;)
Danke

**Comment by Achimobil** [comment]
Ich baue gerade die type liste um dass die aus einer XML gelesen wird um das lesbarer und so zu machen und werde dabei die BigBags enger rücken

**Comment by Achimobil** [comment]
Mit dem Umbau hab ich die geänderten größen wie folge übernommen
`<objectType typeName="bigBag" sizeX="0.95" sizeY="1.55" sizeZ="0.8" type="bigBag" stackable="false" pickupTriggerCollisionMask="TRIGGER_VEHICLE">`

**Comment by andreasthu** [comment]
danke dir
lg
andreas
