### ISSUE TITLE
Frage zum Hinzufügen zum Palletautoloader

### ISSUE THREAD

**Issue by andreasthu** [Achimobil/FS22_aPalletAutoLoader#34]
Hallo Achimobil
ich habe den LS22 crude oil Mod in verwendung
https://www.farming-simulator.com/mod.php?lang=de&country=at&mod_id=276072

nun würde ich daraus gerne die Leeren Ölfässer auch per autoload verladen können, werden aber nicht angenommen.
was muss ich in der emptyBarrel.xml ergänzen damit die genommen werden?
hier die emptyBarrel.xml:

`
<vehicle type="pallet" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../shared/xml/schema/vehicle.xsd">
    <annotation>Copyright (C) GIANTS Software GmbH, All Rights Reserved.</annotation>
    <storeData>
        <name>$l10n_emptyBarrel</name>
		<specs>
            <weight ignore="true"/>
        </specs>
		<functions>
			<function>$l10n_function_emptyBarrel</function>
		</functions>
        <image>pallets/store_emptyBarrel.dds</image>
        <price>20</price>
        <allowLeasing>false</allowLeasing>
        <canBeSold>false</canBeSold>
        <rotation>0</rotation>
        <brand>LIZARD</brand>
        <category>pallets</category>
        <financeCategory>OTHER</financeCategory>
        <shopHeight>1.5</shopHeight>
        <vertexBufferMemoryUsage>33536</vertexBufferMemoryUsage>
        <indexBufferMemoryUsage>7168</indexBufferMemoryUsage>
        <textureMemoryUsage>1572864</textureMemoryUsage>
        <audioMemoryUsage>0</audioMemoryUsage>
        <instanceVertexBufferMemoryUsage>0</instanceVertexBufferMemoryUsage>
        <instanceIndexBufferMemoryUsage>0</instanceIndexBufferMemoryUsage>
    </storeData>

    <base>
        <typeDesc>$l10n_typeDesc_pallet</typeDesc>	
        <filename>pallets/emptyBarrel.i3d</filename>
        <size width="0.5" length="0.5" height="0.9"/>
        <canBeReset>true</canBeReset>
        <components maxMass="10">
            <component centerOfMass="0 0.3 0" solverIterationCount="10" mass="30" />
        </components>
        <showInVehicleMenu>false</showInVehicleMenu>
        <mapHotspot available="true" />        
    </base>

    <pallet fillUnitIndex="1" node="emptyBarrel_vis">
        <content>
            <object node="oilBarrel01"     tensionBeltNode="oilBarrel01Tension"   />
        </content>                                              

        <sounds>
            <unload template="palletsFillBag" pitchScale="0.7" />
        </sounds>
    </pallet>
	
    <fillUnit>
        <fillUnitConfigurations>
            <fillUnitConfiguration name="$l10n_configuration_valueDefault">
                <fillUnits removeVehicleIfEmpty="true">
                    <fillUnit unitTextOverride="$l10n_unit_literShort" fillTypes="EMPTYBARREL" capacity="150" startFillType="EMPTYBARREL" startFillLevel="150" ignoreFillLimit="true">
                        <fillRootNode node="0>" />
                    </fillUnit>
                </fillUnits>
            </fillUnitConfiguration>
        </fillUnitConfigurations>
    </fillUnit>

    <dischargeable requiresTipOcclusionArea="false">
        <dischargeNode node="raycastNode" emptySpeed="150" fillUnitIndex="1" maxDistance="6" canStartDischargeAutomatically="true">
            <raycast useWorldNegYDirection="true" />
            <info width="0.4" length="0.4" />
            <activationTrigger node="dischargeActivationTrigger" />
        </dischargeNode>
    </dischargeable>

    <fillTriggerVehicle triggerNode="fillTrigger" fillUnitIndex="1" litersPerSecond="5"/>

    <dynamicMount triggerNode="dynamicMountTrigger" />

    <i3dMappings>
        <i3dMapping id="emptyBarrel_component1" node="0>" />
        <i3dMapping id="emptyBarrel_vis" node="0>0" />
        <i3dMapping id="dynamicMountTrigger" node="0>0|0" />
		<i3dMapping id="raycastNode" node="0>0|4|0" />
		<i3dMapping id="fillTrigger" node="0>0|4|1" />
		<i3dMapping id="dischargeActivationTrigger" node="0>0|4|2" />
		<i3dMapping id="oilBarrel01" node="0>0|2|0" />
		<i3dMapping id="oilBarrel01Tension" node="0>0|2|0|0" />
    </i3dMappings>
</vehicle>
`

lg
andreas

**Comment by andreasthu** [comment]
Edit:
Hab das wiki gefunden und werde versuchen es umzusetzen.
Frage dazu:
Werde die Fässer als Bigbags definieren, weil sie ja kleiner als Paletten sind,
Bei:
* Bigbags
i3dMappings muss den Eintrage "bigBag_vis" enthalten
XML Datei muss in einem Verzeichnis mit Namen "bigBag" liegen

Muss das bigBag_vis in der i3d an einen bestimmten Platz, reicht da eine TG, oder muss es ein Objekt (ev mit Colli, wenn ja welche) sein?

Lg
Andreas

**Comment by andreasthu** [comment]
Hallo Achimobil
habe da gestern abend und heute noch drann getüftelt:
den ordner paletten auf "euroPallets" geändert,
dann einen ordner "bigBag" erstellt und die emptyPallets da rein verschoben,
pfade in der "mod.desc" und der "newfilltypes.xml" angepasst,
die 5 palleten xml´s haben gepasst, auch der "pallet_vis" war in den i3d enthalten.
diese funktionierten auf Anhieb:
![fsScreen_2024_05_09_05_22_28](https://github.com/Achimobil/FS22_aPalletAutoLoader/assets/24860501/6f810548-9a20-4404-88cd-f30000e33567)
![fsScreen_2024_05_09_05_23_28](https://github.com/Achimobil/FS22_aPalletAutoLoader/assets/24860501/64ff2d93-b794-4471-af22-c313836747fc)
![fsScreen_2024_05_09_05_23_31](https://github.com/Achimobil/FS22_aPalletAutoLoader/assets/24860501/2465d8c6-7ee1-41e4-a8c4-01b8578fda56)

bei den leeren fässern ( alsBigbags) war es etwas aufwändiger,
habe diese als Bigbags in der xml definiert, an einigen Stellen, auch die i3d entsprechend geändert  (bigBag_vis)
schlußendlich noch eine " emptyBarrel_MP.xml" gemacht als "multipleItemPurchase" um mehrere Fässer gleichzeitig kaufen zu können.
damit hatte ich mehrere Probleme, die ich alle bis auf eines lösen konnte.
Einzelfass gekauft, verladen und abgeladen:
![fsScreen_2024_05_09_05_25_44](https://github.com/Achimobil/FS22_aPalletAutoLoader/assets/24860501/5aa7e83d-436f-46c1-ac17-d7ceab43f408)
![fsScreen_2024_05_09_05_26_01](https://github.com/Achimobil/FS22_aPalletAutoLoader/assets/24860501/dd5a0bf3-cdcb-410a-a484-083580b32e03)
![fsScreen_2024_05_09_05_26_14](https://github.com/Achimobil/FS22_aPalletAutoLoader/assets/24860501/0c091fcf-f325-4d68-b04e-20093ce86c04)

und hier mit den multipleItemPurchase Fässern:
![fsScreen_2024_05_09_05_28_41](https://github.com/Achimobil/FS22_aPalletAutoLoader/assets/24860501/b29d91a0-be6d-47d9-a83f-e116e02c1e19)
![fsScreen_2024_05_09_05_28_57](https://github.com/Achimobil/FS22_aPalletAutoLoader/assets/24860501/f0ecf04d-ac22-4756-86e1-42e0e4f1fd3b)
![fsScreen_2024_05_09_05_29_02](https://github.com/Achimobil/FS22_aPalletAutoLoader/assets/24860501/47255403-277d-4193-8d6a-162e9742686b)

das einzige Problem das ich mit den leeren Fässsern habe ist die automatische Erkennung, also STRG+ALT+Y - "Automatisch Ladegut selektieren" funktioniert nicht:
![fsScreen_2024_05_09_05_31_18](https://github.com/Achimobil/FS22_aPalletAutoLoader/assets/24860501/6471023b-4ff6-4640-b388-78e0e212db3b)
hier ist es in der hilfe eingeblendet

wenn ich z.b. auf Europaletten stelle und hinfahre:
![fsScreen_2024_05_09_05_48_36](https://github.com/Achimobil/FS22_aPalletAutoLoader/assets/24860501/3378976e-c892-4929-b529-7ca8392217dc)
wird der key command in der Hilfe nichtmal angeführt und funktioniert auch nicht
die leeren Fässer kann ich nur manuell anwählen.

bei den Palletten hingegen funktioniert es:
![fsScreen_2024_05_09_05_51_20](https://github.com/Achimobil/FS22_aPalletAutoLoader/assets/24860501/5623b269-dbc3-48d0-93c0-98eea714f12e)
![fsScreen_2024_05_09_05_51_26](https://github.com/Achimobil/FS22_aPalletAutoLoader/assets/24860501/005cf51d-cd5c-4130-9b7b-30f6dcd8ac72)

ich häng hier als zip mal meine änderungen drann, ev hast du eine idee:
[meine_anpassungen.zip](https://github.com/Achimobil/FS22_aPalletAutoLoader/files/15257318/meine_anpassungen.zip)

lg
andreas

**Comment by Achimobil** [comment]
Erst mal schön dass du vorran gekommen bist.
Also BigBags sind das nicht, das sind eigene Paleten mit einer Eigenen größe.
So was müsste dann über eine Extension in den Mod wo die her sind eingefügt werden. Siehe z.B. die Straw harvest extension.
Wenn du neben den leeren Fässern stehst zeigt der AL nicht an dass etwas da ist, also werden die Paletten nicht als Paletten erkannt und der Befehl für die Automatic wird nicht eingeblendet. Da fehlt den Paletten etwas um ohne Vehicle Trigger erkannt zu werden. Auf anhieb weiß ich nicht mehr was das war, aber es hat was mit den nodes in der i3d und den collission masks zu tun.

**Comment by andreasthu** [comment]
Hallo Achimobil.
Das automatische erkennen ist mir jetztmal eh nicht wichtig.
Wie gesagt, ich wähle BigBags manuell an und kann die leeren Fässer verladen, Transportieren und am endpunkt abladen.
Also für mich funktioniert es.
Lg
Andreas

**Comment by Achimobil** [comment]
Wenn dir das aus reicht, dann können wir das ticket ja schließen.
Wenn du willst dass dies alle können so wie du, dann solltest du das mal an den Modder von den Paletten schicken, hier wird er das wohl nicht finden.

**Comment by andreasthu** [comment]
Hallo achimobil
Werds mal versuchen, BartsoNv3 ist scheinbar nicht im giants forum, es gibt aber auf facebook eine modding seite, polnisch, oder osteuropa, das wird interessant.
https://www.google.com/search?q=BartsoNv3&client=ms-android-samsung-ss&sourceid=chrome-mobile&ie=UTF-8&chrome_dse_attribution=1
Mal schaun obs was wird.
Lg
Andreas

**Comment by andreasthu** [comment]
Hallo Achim.
Kurzes Update, hab von BartsoNv3 noch keine Rückmeldung erhalten, ev wirds später noch was.

2. Ist es möglich, für AL eigene Palettentypen zu konfigurieren, also quasi direkt im öl- mod, das ich da eine eigene Kategorie "Barrel" definiere, ausgehend von der Bigbag Kategorie, nur mit weniger Abstand und stapelbar?
Oder muss ich sowas in deinen mod direkt einbauen?
Hab im AL Wiki nichts dazu gefunden.
Lg
Andreas

**Comment by Achimobil** [comment]
Also erst mal manche Modder wollen auf anfragen einfach nicht reagieren und andere sind einfach nicht mehr da.
Das ist schade, den ich denke wenn man einen Mod veröffentlicht, dann hat man dafür auch eine gewisse Verantwortung.
Ich hoffe du erreichst da noch was.

Ja, man kann da was machen. Ich habe die Möglichkeit der Erweiterung über andere Mods eingebaut. Dokumentation gibt's nicht aber ein Beispielprojekt das auch funktioniert von mir. Hierbei wird eine lua entweder als separater mod oder direkt in den Mod eingebaut. Der Modder von dem Öl Mod könnte also eine lua einfügen die den Autoload erweitert. Wenn du es nur für dich machst kannst du das natürlich auch, darfst aber ohne Freigabe vom Öl Mod Ersteller nicht veröffentlichen. Oder als separater Mod mit eigenem Bild und so, dass du dann veröffentlichen darfst, weil du nix vom AL oder dem Öl Mod da rein kopierst. Ich hoffe das war so verständlich. 

Im Prinzip fügt man über lua code weitere Definitionen dem AL zu. 
Ich hab gerade den AL Haupt Mod umgestellt auf Laden aus einer XML, ob das für Extension machbar ist weiß ich noch nicht.
Wie das geht kannst du dir in der HB Erweiterung anschauen, einfach mal runter laden und schauen wie das da so gemacht ist.
https://github.com/Achimobil/FS22_aPalletAutoLoader_Extension_HofBergmann

**Comment by andreasthu** [comment]
Danke dir Achim
hat erstmal funktioniert:
![fsScreen_2024_06_05_10_32_29](https://github.com/Achimobil/FS22_aPalletAutoLoader/assets/24860501/5e743352-22e7-4239-95d6-98c419c3d190)
einzig den Namen findet er im F1-Menü nicht
habe die AutoloaderExtension.lua geändert:
[AutoloaderExtension.lua.txt](https://github.com/user-attachments/files/15580900/AutoloaderExtension.lua.txt)
den eintrag in der moddesc:
```
    <extraSourceFiles>
        <sourceFile filename="AutoloaderExtension.lua"/>
    </extraSourceFiles>

```
(vor den storeItems)

und in den l10n dateien 
`		<text name="aPalletAutoLoader_co_barrel"		text="Barrel"/>`
hinzugefügt.
trotzdem findet AL den namen (Barrel) nicht.

btw, in der moddesc sind die l10n so zugewiesen:
`		<l10n filenamePrefix="lang/l10n"/>
`
keine errors bzw warnings dazu in der log
lg
andreas

**Comment by Achimobil** [comment]
Du hast den type "co_Barrel" in der lua genannt aber in der l10n steht "co_barrel". Schreib das auch in der l10n mal mit großem B, sieht sonst gut aus, nur viel mehr kann aus der datei noch gelöscht werden ;)

**Comment by andreasthu** [comment]
ah ja danke, da bin ich ein kleiner Rechtsschreib-Legastheniker.
sowas seh ich beim nachprüfen auch nie :-(



> ...sieht sonst gut aus, nur viel mehr kann aus der datei noch gelöscht werden ;)

meinst du in der   AutoloaderExtension.lua ?
ich kann leider kein lua, hab das so gemacht wie ich glaubte das ich das brauch.
was ist zuviel?
lg
andreas

**Comment by Achimobil** [comment]
Die unteren Methoden sind zuviel, weil werden nicht mehr gebraucht, stören aber auch nicht wenn du sie für dich drin lässt
