### ISSUE TITLE
can't autocheck "bigBag" 

### ISSUE THREAD

**Issue by ppopcn** [Achimobil/FS22_aPalletAutoLoader#36]
can't autocheck "bigBag" 
need to Manual selection

**Comment by Achimobil** [comment]
Sometimes it works and sometimes not. That is because bigbars are faulty defined and in the LS no pallets with for pallets correct collision boxes. And therefore it sometimes works and sometimes not. Only the modder ot den bigbag can change that, which ist mostly Giants
