### ISSUE TITLE
In v1.13.0.0 (maybe earlier) "Euro pallets overloaded" stopped loading.

### ISSUE THREAD

**Issue by vitalii2011** [Achimobil/FS22_aPalletAutoLoader#37]
Basic pallet and tractor. Trailer Strautmann SEK 802 Pallet Autoload v1.7.0.0.
![fsScreen_2024_08_25_12_11_50](https://github.com/user-attachments/assets/c36497ac-70cd-439e-999d-a37f5c6f2963)
I didn't see anything related to this in the error log:
[log.txt](https://github.com/user-attachments/files/16739624/log.txt)

**Comment by Achimobil** [comment]
When you change the loading stuff it could happen that the stuff is not seen anymore. You see that in the F1 Menu. Is there shown one pallet? If not have you tried to drive a step away and to it again?
I think when this do not work in generall anymore I would get a lot of messages and this is the first since the last update.

**Comment by vitalii2011** [comment]
Tried with different equipment and trailers.
In F1 it is displayed as it should be.
In the picture, at the top in the middle, you can see 0/7 for Strautmann SEK 802 Pallet Autoload.
Yes, of course, the problem may be due to some new/updated mod. I will try to find the "culprit". If I find it, I will let you know.

**Comment by vitalii2011** [comment]
The problem arises if you drive up to the loading area next to a pallet PLACED BY THE GAME, i.e. purchased or placed (by the game mechanics) for transportation. If the pallet "was already on the trailer", then it is loaded from the closest distance:
[Uploading FarmingSimulator2022Game 2024-08-27 12-30-21-380_0001.zip…]()

**Comment by Achimobil** [comment]
What do you mean with "was already on the trailer" ?
I can buy pallets and load them without any problem in my games.
when a foreign skript moves the pallet from the trailer it will not load it again because it is still marked as loaded. That should be clear

**Comment by vitalii2011** [comment]
Nobody told you anything about "a foreign script". Don't make things up.

**Comment by vitalii2011** [comment]
You buy a tractor (basic), a trailer (trautmann SEK 802 Pallet Autoload), a pallet with seeds (basic) - you hook up the trailer (without moving it) and try to load the pallet, which is located next to the trailer after purchase. Is it possible to load? Or do you just have to drive away and load from a greater distance?

**Comment by vitalii2011** [comment]
P.S.
Yesterday the archive with the video "About the problem" did not load here, so you did not understand everything that I reported.
Watch the video here: https://drive.google.com/file/d/1ANBRigPGs_O_ECnqEdpepHZHl1IupHCc/view?usp=sharing

**Comment by Achimobil** [comment]
I do not have that behavior when I do that. As you can see here:
https://youtu.be/yE5wI6iw0Ns
