### ISSUE TITLE
Will it be updated for FS 25?

### ISSUE THREAD

**Issue by BeReal86** [Achimobil/FS22_aPalletAutoLoader#39]
Hello, @Achimobil  I would like to ask specifically about this mod. Will you update it for FS 25?

**Comment by Achimobil** [comment]
Aktual state is: No. In FS 25 the Universal Autoload from Loki will come when he is ready with it

**Comment by BeReal86** [comment]
Hi @Achimobil 

https://github.com/loki79uk/FS25_UniversalAutoload

Loki has started working on it, I hope it will all be completed soon.

**Comment by Achimobil** [comment]
Yes, and Loki has my contact details and the authorisations to use everything from my autoloader for the new Universal Autoload in the 25 series
