### ISSUE TITLE
Mod not Loading

### ISSUE THREAD

**Issue by RickZurc** [Achimobil/FS22_aPalletAutoLoader#40]
Hi im trying to get these mods running
![image](https://github.com/user-attachments/assets/1f3071b1-307d-4138-bcd7-782b3f1425d5)

But ingame when i try to start a new save gives me this error
![image](https://github.com/user-attachments/assets/8e2d9809-2922-44b2-8303-7860531c3363)
Here's the files
![image](https://github.com/user-attachments/assets/69ce3039-8235-45b6-a418-aa645b070678)

**Comment by Achimobil** [comment]
First check if your FS22 is most recent up to date, so on the newest patch. 
When this is the case then please attach your log here so I can try to see why the AL is not loaded.

**Comment by RickZurc** [comment]
> First check if your FS22 is most recent up to date, so on the newest patch. When this is the case then please attach your log here so I can try to see why the AL is not loaded.

It worked with the updated FS22, my steam is going crazy these days it doesnt like updates.
Thanks for the fast response

**Comment by Achimobil** [comment]
Have fun with the game ;)
